# Generated by Django 2.2.5 on 2020-06-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditrulelist',
            options={'permissions': (('audit_group_editor', '可编辑本组审计数据'), ('audit_export', '可导出部门审计报告')), 'verbose_name': '审计规则列表', 'verbose_name_plural': '审计规则列表'},
        ),
        migrations.AlterField(
            model_name='auditnontrade',
            name='log_date',
            field=models.DateField(blank=True, null=True, verbose_name='操作日期'),
        ),
        migrations.AlterField(
            model_name='auditnontrade',
            name='module_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='模块名称'),
        ),
        migrations.AlterField(
            model_name='auditnontrade',
            name='module_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='模块类型'),
        ),
        migrations.AlterField(
            model_name='auditnontrade',
            name='remark',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='auditothergroupsec',
            name='cnt_date',
            field=models.IntegerField(blank=True, null=True, verbose_name='查询天数'),
        ),
        migrations.AlterField(
            model_name='auditothergroupsec',
            name='cnt_query',
            field=models.IntegerField(blank=True, null=True, verbose_name='查询次数'),
        ),
        migrations.AlterField(
            model_name='auditothergroupsec',
            name='remark',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='auditothergroupsec',
            name='sec_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='股票代码'),
        ),
        migrations.AlterField(
            model_name='auditothergroupsec',
            name='sec_group',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='股票所属组名'),
        ),
        migrations.AlterField(
            model_name='auditothergroupsec',
            name='sys_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='系统名称'),
        ),
        migrations.AlterField(
            model_name='auditothergroupsec',
            name='week_end',
            field=models.DateField(blank=True, null=True, verbose_name='周末'),
        ),
        migrations.AlterField(
            model_name='auditothergroupsec',
            name='week_start',
            field=models.DateField(blank=True, null=True, verbose_name='周初'),
        ),
        migrations.AlterField(
            model_name='auditotherip',
            name='module_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='模块名称'),
        ),
        migrations.AlterField(
            model_name='auditotherip',
            name='module_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='模块类型'),
        ),
        migrations.AlterField(
            model_name='auditotherip',
            name='remark',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='auditqueryaccttype',
            name='module_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='模块名称'),
        ),
        migrations.AlterField(
            model_name='auditqueryaccttype',
            name='module_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='模块类型'),
        ),
        migrations.AlterField(
            model_name='auditqueryaccttype',
            name='remark',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='auditquerysec',
            name='module_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='模块名称'),
        ),
        migrations.AlterField(
            model_name='auditquerysec',
            name='module_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='模块类型'),
        ),
        migrations.AlterField(
            model_name='auditquerysec',
            name='remark',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='auditruledetail',
            name='acct_ids',
            field=models.TextField(blank=True, null=True, verbose_name='账户代码'),
        ),
        migrations.AlterField(
            model_name='auditruledetail',
            name='audit_rule_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='审计规则名称'),
        ),
        migrations.AlterField(
            model_name='auditruledetail',
            name='ip',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ip地址'),
        ),
        migrations.AlterField(
            model_name='auditruledetail',
            name='log_dtl',
            field=models.TextField(blank=True, null=True, verbose_name='日志明细'),
        ),
        migrations.AlterField(
            model_name='auditruledetail',
            name='log_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='操作时间'),
        ),
        migrations.AlterField(
            model_name='auditruledetail',
            name='module_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='模块名称'),
        ),
        migrations.AlterField(
            model_name='auditruledetail',
            name='module_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='模块类型'),
        ),
        migrations.AlterField(
            model_name='auditruledetail',
            name='sec_codes',
            field=models.TextField(blank=True, null=True, verbose_name='股票代码'),
        ),
        migrations.AlterField(
            model_name='auditruledetail',
            name='sys_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='系统名称'),
        ),
    ]
