# Generated by Django 3.2.20 on 2023-08-17 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Component', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appexecutehistory',
            options={'ordering': ('-id',), 'permissions': (('view_all', '查看全部记录'), ('view_group', '查看本组记录'), ('view_log', '查看日志'), ('kill_pid', '关闭进程')), 'verbose_name': '应用执行历史', 'verbose_name_plural': '应用执行历史'},
        ),
    ]
