# Generated by Django 2.2.5 on 2020-07-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NormalTask', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sqlcode',
            name='replace_style',
            field=models.IntegerField(choices=[(0, '%(name)s'), (1, '#{name}'), (2, '&name')], default=0, help_text='占位符替换风格', verbose_name='占位符替换风格'),
        ),
    ]
