# Generated by Django 2.2.5 on 2023-08-25 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NormalTask', '0002_auto_20200721_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parenttask',
            name='type',
            field=models.CharField(choices=[('query', (('research', 'research'), ('routine', 'routine'))), ('file', (('inquery', 'inquery'), ('measure', 'measure')))], max_length=100, verbose_name='需求类型'),
        ),
    ]
